
"use client";
import type { Language } from '@/types';
import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: Record<string, string | number | null | undefined>, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translations store
const translations: Record<Language, Record<string, string>> = {
  mn: {
    bookNowButton: "Захиалах",
    orderNowButton: "Одоо захиалах",
    inquireButton: "Судлуулах",
    orderSuccessNotificationTitle: "Захиалга амжилттай",
    orderSuccessNotificationDescription: "{{serviceName}} үйлчилгээний захиалга баталгаажлаа.",
    orderFailedNotificationTitle: "Захиалга амжилтгүй",
    orderFailedNotificationDescription: "{{serviceName}} үйлчилгээг захиалахад алдаа гарлаа.",
    loginToProceed: "Үргэлжлүүлэхийн тулд нэвтэрнэ үү.",
    loginToBookService: "Үйлчилгээ захиалахын тулд нэвтэрнэ үү.",
    // Header & Nav
    citySelectorPlaceholder: "Хот сонгох",
    citySelectorAriaLabel: "Хот сонгогч",
    allCities: "Бүгд",
    login: "Нэвтрэх",
    register: "Бүртгүүлэх",
    logout: "Гарах",
    profile: "Профайл",
    home: "Нүүр",
    orders: "Захиалга",
    saved: "Хадгалсан",
    notifications: "Мэдэгдэл",
    user: "Хэрэглэгч", // For BottomNav
    // Service Groups
    flights: "Нислэг",
    hotels: "Буудал",
    translators: "Орчуулагч",
    wechat: "WeChat",
    markets: "Зах, худалдаа",
    factories: "Үйлдвэр",
    hospitals: "Эмнэлэг",
    embassies: "Элчин сайд",
    // Suggested Services Titles
    recommended_translators: "Санал болгох орчуулагчид",
    recommended_hotels: "Санал болгох буудлууд",
    recommended_markets: "Санал болгох зах",
    recommended_factories: "Санал болгох үйлдвэр",
    recommended_hospitals: "Санал болгох эмнэлэг",
    recommended_embassies: "Санал болгох элчин сайд",
    recommendedWeChatServices: "Санал болгох WeChat",
    // General
    loading: "Ачааллаж байна...",
    viewAll: "Бүгдийг харах",
    noRecommendations: "Санал болгох зүйл олдсонгүй.",
    search: "Хайх",
    searchPlaceholder: "Хайх",
    serviceTypes: "Үйлчилгээний төрөл",
    viewDetails: "Дэлгэрэнгүй",
    addToFavorites: "Хадгалах",
    removeFromFavorites: "Хадгалсан зүйлсээс устгах",
    fetchErrorGeneric: "Өгөгдөл татахад алдаа гарлаа.",
    serviceImageDefaultAlt: "Үйлчилгээний зураг",
    serviceUnnamed: "Нэргүй үйлчилгээ",
    // Banners (example alt texts)
    banner_promo1_alt: "Урамшуулал 1",
    banner_promo2_alt: "Онцлох үйлчилгээ",
    // Page specific
    myOrders: "Миний захиалгууд",
    mySavedItems: "Миний хадгалсан зүйлс",
    myNotifications: "Миний мэдэгдлүүд",
    noOrdersPlaceholder: "Танд одоогоор захиалга байхгүй байна.",
    ordersNoPurchasesMade: "Та худалдан авалт хийгээгүй байна",
    wechatOrdersTab: "WeChat",
    noSavedItemsPlaceholder: "Танд одоогоор хадгалсан зүйл байхгүй байна.",
    noNotificationsPlaceholder: "Танд одоогоор мэдэгдэл байхгүй байна.",
    email: "И-мэйл",
    password: "Нууц үг",
    displayName: "Нэр",
    confirmPassword: "Нууц үг давтах",
    alreadyHaveAccount: "Бүртгэлтэй юу? Нэвтрэх",
    dontHaveAccount: "Бүртгэлгүй юу? Бүртгүүлэх",
    // Profile & Settings
    settings: "Тохиргоо",
    notificationSettings: "Мэдэгдлийн тохиргоо",
    manageNotificationPreferences: "И-мэйл болон апп-ын мэдэгдлээ удирдаарай.",
    emailNotifications: "И-мэйл мэдэгдэл",
    receiveUpdatesViaEmail: "И-мэйлээр шинэчлэлтүүдийг хүлээн авах.",
    pushNotifications: "Түргэн мэдэгдэл",
    getRealtimeAppAlerts: "Апп-аас бодит цагийн мэдэгдэл авах.",
    appearanceSettings: "Гадаад үзэмжийн тохиргоо",
    customizeAppLook: "Аппликейшний харагдах байдлыг өөрчлөх.",
    darkMode: "Харанхуй горим",
    enableDarkTheme: "Харанхуй дэвсгэртэй горим идэвхжүүлэх.",
    accountSecurity: "Бүртгэлийн аюулгүй байдал",
    manageSecuritySettings: "Нууц үг болон бусад аюулгүй байдлын тохиргоо.",
    currentPassword: "Одоогийн нууц үг",
    newPassword: "Шинэ нууц үг",
    updatePassword: "Нууц үг шинэчлэх",
    saveAllSettings: "Бүх тохиргоог хадгалах",
    saveChanges: "Өөрчлөлтийг хадгалах",
    cancel: "Цуцлах",
    edit: "Засах",
    accountSettings: "Бүртгэлийн тохиргоо",
    userProfile: "Хэрэглэгчийн профайл",
    enterCredentialsLogin: "Нэвтрэхийн тулд мэдээллээ оруулна уу.",
    createYourAccount: "Mongol-д бүртгүүлээрэй.",
    // Notification specific
    notification_update_title: "Системийн шинэчлэл",
    notification_update_desc: "Аппликейшн шинэчлэгдлээ. Шинэ боломжуудтай танилцана уу.",
    unknownNotificationTitle: "Мэдэгдэл",
    unknownNotificationDescription: "Танд шинэ мэдэгдэл ирлээ.",
    translatorContactRevealedNotificationDescription: "Орчуулагч {{serviceName}}: Утас: {{translatorPhoneNumber}}, WeChat: {{translatorWeChatId}}.",
    // Flight Search Page
    flightsPageTitle: "Нислэг",
    selectDepartureDate: "Нисэх өдрөө сонгоно уу",
    selectDatePlaceholder: "Огноо сонгох",
    passengers: "Зорчигч",
    onePassenger: "1 зорчигч",
    twoPassengers: "2 зорчигч",
    threePassengers: "3 зорчигч",
    fourPassengers: "4 зорчигч",
    searchFlights: "Нислэг хайх",
    swapAirports: "Чиглэл солих",
    back: "Буцах",
    fromCity: "Хаанаас (Хот)",
    toCity: "Хаашаа (Хот)",
    departureCityPlaceholder: "Явах хот сонгох",
    arrivalCityPlaceholder: "Очих хот сонгох",
    departureCityRequired: "Явах хотыг сонгоно уу",
    arrivalCityRequired: "Очих хотыг сонгоно уу",
    selectCityDialogTitle: "Хот сонгох",
    searchCitiesPlaceholder: "Хот хайх",
    noCitiesFound: "Хот олдсонгүй",
    // Hotels Page
    hotelsPageTitle: "Зочид буудал",
    allSectionTitle: "Бүгд",
    fetchHotelsError: "Буудлын мэдээлэл татахад алдаа гарлаа.",
    noHotelsFound: "Сонгосон хотод зочид буудал олдсонгүй.",
    loginToBookHotel: "Буудал захиалахын тулд нэвтэрнэ үү.",
    // Profile Page
    profilePageTitle: "Хэрэглэгч",
    personalInfo: "Хувийн мэдээлэл",
    personalInfoProgress: "Хувийн мэдээлэл {{percent}} бөглөсөн",
    totalPoints: "Таны нийт оноо",
    phoneNumber: "Утасны дугаар",
    changePassword: "Нууц үг солих",
    purchaseHistory: "Худалдан авалтын түүх",
    registerAsTranslator: "Орчуулагчаар бүртгүүлэх",
    helpSupport: "Тусламж",
    logoutSystem: "Системээс гарах",
    n_a: "N/A",
    enterPhoneNumberPlaceholder: "Утасны дугаараа оруулна уу",
    phoneNumberUpdateSuccess: "Утасны дугаар амжилттай шинэчлэгдлээ.",
    phoneNumberUpdateError: "Утасны дугаар шинэчлэхэд алдаа гарлаа.",
    // Translators Page
    translatorsPageTitle: "Орчуулагч",
    translatorsSectionTitle: "Орчуулагчид",
    addTranslator: "Орчуулагч нэмэх",
    statusActive: "Идэвхтэй",
    монгол: "Монгол",
    идэвхтэй: "Идэвхтэй",
    testLevel: "Шалгалтын түвшин",
    speaking: "Яриа",
    writing: "Бичиг",
    workedBefore: "Ажиллаж байсан",
    yes: "Тийм",
    no: "Үгүй",
    fields: "Чиглэл",
    price: "Үнэ",
    // Hospitals Page
    hospitalsPageTitle: "Эмнэлэг",
    allHospitalsSectionTitle: "Эмнэлгүүд",
    // Embassies Page
    embassiesPageTitle: "Элчин сайд",
    embassiesListingTitle: "Элчин сайдын яамд/Консулын газрууд",
    // WeChat Page
    wechatPageTitle: "Хэрэгцээт WeChat",
    // Factories Page
    factoriesPageTitle: "Үйлдвэр",
    allFactoriesSectionTitle: "Үйлдвэрүүд",
    productShowcaseTitle: "Бүтээгдэхүүний танилцуулга",
    productImageAlt: "Бүтээгдэхүүний зураг",
    noProductDescription: "Бүтээгдэхүүний тайлбар байхгүй.",
    // Markets Page
    marketsPageTitle: "Зах, худалдаа",
    allMarketsSectionTitle: "Захууд ба худалдааны төвүүд",
    // Save/Favorite functionality
    loginToSave: "Хадгалахын тулд нэвтэрнэ үү",
    itemSaved: "Амжилттай хадгаллаа",
    itemRemovedFromSaved: "Хадгалснаас амжилттай устгалаа",
    errorSavingItem: "Зүйлийг хадгалахад алдаа гарлаа",
    errorRemovingItem: "Зүйлийг хадгалснаас устгахад алдаа гарлаа",
    errorCheckingSaveStatus: "Хадгалсан төлөв шалгахад алдаа гарлаа",
    registrationSuccess: "Бүртгэл амжилттай",
    welcome: "Тавтай морилно уу!",
    registrationFailed: "Бүртгэл амжилтгүй боллоо",
    registrationError: "Бүртгүүлэх явцад алдаа гарлаа.",
    error: "Алдаа",
    passwordsDoNotMatchError: "Нууц үг таарахгүй байна.",
    registrationSuccessVerifyEmail: "Баталгаажуулах линк таны имэйл хаяг руу илгээлээ. Нэвтрэхээсээ өмнө имэйлээ шалгана уу.",
    loginFailed: "Нэвтрэхэд алдаа гарлаа",
    loginFailedEmailNotVerified: "Имэйл хаяг баталгаажаагүй байна. Имэйлээ шалгаж, баталгаажуулна уу.",
    // Password Update specific
    changePasswordPageTitle: "Нууц үг солих",
    currentPasswordLabel: "Хуучин нууц үг",
    newPasswordLabel: "Шинэ нууц үг",
    confirmNewPasswordLabel: "Шинэ нууц үг давтах",
    currentPasswordPlaceholder: "Хуучин нууц үг",
    newPasswordPlaceholder: "Шинэ нууц үг",
    confirmNewPasswordPlaceholder: "Шинэ нууц үг давтах",
    passwordUpdateSuccess: "Нууц үг амжилттай шинэчлэгдлээ!",
    passwordUpdateError: "Нууц үг шинэчлэхэд алдаа гарлаа.",
    reauthFailedError: "Одоогийн нууц үг буруу байна. Дахин шалгана уу.",
    passwordTooWeakError: "Нууц үг хэт сул байна. Хамгийн багадаа 6 тэмдэгт байх ёстой.",
    passwordTooWeakErrorGeneral: "Нууц үг хэт сул байна. Илүү хүчтэй нууц үг сонгоно уу.",
    genericPasswordError: "Нууц үг шинэчлэх явцад гэнэтийн алдаа гарлаа.",
    userNotLoggedInError: "Хэрэглэгч нэвтрээгүй байна.",
    passwordRequiresRecentLogin: "Энэ үйлдэл нь нууцлалтай тул саяхан нэвтэрсэн байхыг шаарддаг. Дахин нэвтэрч оролдоно уу.",
    settingsSavedMsg: "Тохиргоо амжилттай хадгалагдлаа (нууц үгнээс бусад).",
    passwordReqLength_8_50: "8 - 50 тэмдэгтэнд багтаах",
    passwordReqComplexity: "Дор хаяж 1 том үсэг, 1 жижиг үсэг, 1 тоо, 1 тусгай тэмдэгт орсон байх",
    passwordReqSpecialCharsDetail: "Боломжит тусгай тэмдэгтүүд: {{chars}}",
    passwordReqUppercase: "Том үсэг: A-Z",
    passwordReqLowercase: "Жижиг үсэг: a-z",
    passwordReqMatch: "Хоёр нууц үг адилхан байх",
    passwordReqLengthError: "Нууц үг 8-50 тэмдэгт хооронд байх ёстой.",
    passwordReqUppercaseError: "Нууц үг дор хаяж нэг том үсэг агуулсан байх ёстой (A-Z).",
    passwordReqLowercaseError: "Нууц үг дор хаяж нэг жижиг үсэг агуулсан байх ёстой (a-z).",
    passwordReqNumberError: "Нууц үг дор хаяж нэг тоо агуулсан байх ёстой (0-9).",
    passwordReqSpecialCharError: "Нууц үг дор хаяж нэг тусгай тэмдэгт агуулсан байх ёстой.",
    continueButton: "Үргэлжлүүлэх",
    // Translator Registration
    registerAsTranslatorPageTitle: "Орчуулагчаар бүртгүүлэх",
    translatorRegistrationFormTitle: "Орчуулагчийн мэдээлэл",
    translatorRegistrationFormDescription: "Орчуулагчийн мэдээллээ оруулж бүртгүүлнэ үү.",
    submitRegistration: "Бүртгүүлэх",
    registrationSuccessful: "Амжилттай бүртгүүллээ!",
    registrationFailedGeneral: "Бүртгэл амжилтгүй боллоо. Дахин оролдоно уу.",
    fillAllFields: "Шаардлагатай бүх талбарыг бөглөнө үү.",
    mustBeLoggedInToRegister: "Орчуулагчаар бүртгүүлэхийн тулд нэвтэрсэн байх шаардлагатай.",
    translatorFormStep1: "Үндсэн мэдээлэл",
    translatorFormStep2: "Баримт бичиг",
    nationalityLabel: "Иргэншил",
    selectNationalityPlaceholder: "Иргэншилээ сонгоно уу",
    mongolian: "Монгол",
    chinese: "Хятад",
    innerMongolian: "Өвөрмонгол",
    inChinaNowLabel: "Та одоо Хятад улсад байгаа юу?",
    yearsInChinaLabel: "Хятад улсад хэдэн жил амьдарсан бэ?",
    yearsInChinaPlaceholder: "Жилийн тоо",
    currentCityInChinaLabel: "Хятадын аль хотод байгаа вэ?",
    selectCurrentCityInChinaPlaceholder: "Хот сонгоно уу",
    chineseExamTakenLabel: "Хятад хэлний шалгалт өгч байсан уу?",
    chineseExamDetailsLabel: "Шалгалтын нэр/түвшин",
    speakingLevelLabel: "Ярианы түвшин",
    selectSpeakingLevelPlaceholder: "Ярианы түвшнээ сонгоно уу",
    writingLevelLabel: "Бичгийн түвшин",
    selectWritingLevelPlaceholder: "Бичгийн түвшнээ сонгоно уу",
    languageLevelGood: "Сайн",
    languageLevelIntermediate: "Дунд",
    languageLevelBasic: "Анхан",
    workedAsTranslatorLabel: "Орчуулга хийж байсан уу?",
    translationFieldsLabel: "Орчуулга хийх боломжтой салбарууд",
    fieldTourism: "Аялал зугаалга",
    fieldMedical: "Эмнэлэг, эмчилгээ",
    fieldEquipment: "Тоног төхөөрөмж",
    fieldExhibition: "Үзэсгэлэн худалдаа",
    fieldOfficialDocuments: "Албан бичгийн орчуулга",
    fieldOfficialSpeech: "Албан ярианы орчуулга",
    fieldMachinery: "Машин механизм",
    canWorkInOtherCitiesLabel: "Бусад хотод ажиллах боломжтой эсэх",
    dailyRateLabel: "Таны 1 өдрийн орчуулга хийх үнэ/тариф (юань)",
    selectDailyRatePlaceholder: "Үнийн дүнгээ сонгоно уу",
    rate100to200: "100-200 юань",
    rate200to300: "200-300 юань",
    rate300to400: "300-400 юань",
    rate400to500: "400-500 юань",
    rate500plus: "500+ юань",
    chinaPhoneNumberLabel: "Хятад утасны дугаар",
    chinaPhoneNumberPlaceholder: "Утасны дугаар",
    wechatIdLabel: "WeChat ID",
    wechatIdPlaceholder: "WeChat ID",
    nextStepButton: "Дараагийн алхам",
    previousStepButton: "Өмнөх алхам",
    idCardFrontImageLabel: "Иргэний үнэмлэхний урд талын зураг",
    idCardBackImageLabel: "Иргэний үнэмлэхний ард талын зураг",
    selfieImageLabel: "Өөрийн нүүр зураг (селфи)",
    wechatQrImageLabel: "WeChat QR кодны зураг",
    selectFileButton: "Файл сонгох",
    fileSelected: "{{fileName}} сонгогдлоо",
    noFileSelected: "Файл сонгоогүй байна",
    uploadImagesDescription: "Шаардлагатай зургуудыг оруулна уу.",
    submitApplicationButton: "Анкет илгээх",
    applicationSubmittedSuccessTitle: "Анкет амжилттай илгээгдлээ!",
    applicationSubmittedSuccessDescription: "Таны мэдээллийг бид хүлээн авлаа. Удахгүй тантай холбогдох болно.",
    backToProfileButton: "Профайл руу буцах",
    fileSizeError: "{{fileName}} файлын хэмжээ хэтэрсэн (Макс: 5MB).",
    idCardFrontImageSizeError: "Иргэний үнэмлэхний урд талын зургийн хэмжээ хэтэрсэн (Макс: 5MB).",
    idCardBackImageSizeError: "Иргэний үнэмлэхний ард талын зургийн хэмжээ хэтэрсэн (Макс: 5MB).",
    selfieImageSizeError: "Нүүр зургийн хэмжээ хэтэрсэн (Макс: 5MB).",
    wechatQrImageSizeError: "WeChat QR зургийн хэмжээ хэтэрсэн (Макс: 5MB).",
    requiredError: "Энэ талбарыг заавал бөглөнө үү.",
    invalidNumberError: "Хүчинтэй тоо оруулна уу.",
    // Help & Support Page
    helpSupportPageTitle: "Тусламж",
    helpSupportPageSubtitle: "Танд тулгарч буй асуудлаар бидэнтэй холбогдоорой эсвэл түгээмэл асуултуудтай танилцана уу.",
    faqTitle: "Түгээмэл Асуултууд",
    faqSubtitle: "Олон хэрэглэгчдийн сонирхдог асуулт, хариултууд.",
    contactSupportTitle: "Холбоо Барих",
    contactSupportSubtitle: "Бид танд туслахад бэлэн байна.",
    emailSupportTitle: "И-мэйлээр холбогдох",
    emailSupportDescription: "Асуулт, саналаа бидэнд илгээнэ үү.",
    phoneSupportTitle: "Утсаар холбогдох",
    phoneSupportDescription: "Яаралтай тусламж хэрэгтэй бол залгаарай.",
    noFaqsAvailable: "Одоогоор түгээмэл асуулт байхгүй байна.",
    helpFaq1Question: "Яаж нууц үгээ солих вэ?",
    helpFaq1Answer: "Профайлын тохиргоо хэсэгт ороод 'Нууц үг солих' сонголтыг дарж, зааврын дагуу шинэ нууц үгээ оруулна.",
    helpFaq2Question: "Орчуулагчаар хэрхэн бүртгүүлэх вэ?",
    helpFaq2Answer: "Профайл хуудасны 'Орчуулагчаар бүртгүүлэх' цэсрүү орж, шаардлагатай мэдээллээ бөглөнө.",
    helpFaq3Question: "Хадгалсан зүйлсээ хаанаас харах вэ?",
    helpFaq3Answer: "Доод цэсний 'Хадгалсан' дүрс дээр дарж хадгалсан бүх үйлчилгээ, бараагаа харах боломжтой.",
    faqTopicAppUsage: "Аппликэйшн ашиглах заавар",
    faqTopicCheapTravel: "Хэрхэн хямд аялах вэ?",
    termsOfService: "Үйлчилгээний нөхцөл",
    privacyPolicy: "Нууцлалын баталгаа",
    otherInformationTitle: "Бусад мэдээлэл",
    // Personal Information Form
    personalInfoFormTitle: "Хувийн мэдээлэл",
    personalInfoFormDescription: "Хувийн мэдээллээ оруулна уу.",
    lastName: "Овог",
    yourLastNamePlaceholder: "Таны овог",
    firstName: "Нэр",
    yourFirstNamePlaceholder: "Таны нэр",
    dateOfBirth: "Төрсөн огноо",
    selectDatePlaceholderShort: "Огноо сонгох",
    gender: "Хүйс",
    selectGenderPlaceholder: "Хүйс сонгоно уу",
    male: "Эрэгтэй",
    female: "Эмэгтэй",
    other: "Бусад",
    homeAddress: "Гэрийн хаяг",
    yourHomeAddressPlaceholder: "Таны гэрийн хаяг",
    save: "Хадгалах",
    personalInfoUpdateSuccess: "Хувийн мэдээлэл амжилттай шинэчлэгдлээ.",
    personalInfoUpdateError: "Хувийн мэдээлэл шинэчлэхэд алдаа гарлаа.",
    fillRequiredFields: "Заавал бөглөх талбарыг оруулна уу.",
    // Translator Detail Page
    translatorDetailTitle: "Орчуулагчийн мэдээлэл",
    translatorNotFound: "Орчуулагч олдсонгүй.",
    getContactInfoButton: "Холбоо барих мэдээлэл авах",
    contactInfoPaymentPlaceholder: "Төлбөр төлсний дараа холбоо барих мэдээлэл харагдана.",
    paymentModalTitle: "Төлбөр хийх",
    paymentModalDescription: "{{rate}} юанийн төлбөр хийснээр орчуулагчийн холбоо барих мэдээллийг авах боломжтой.",
    paymentModalDescriptionNoRate: "Орчуулагчийн холбоо барих мэдээллийг авахад үйлчилгээний хураамж төлнө.",
    payButton: "Төлөх",
    orderCreatedSuccess: "Захиалга амжилттай үүслээ!",
    contactInfoAvailableInOrders: "Холбоо барих мэдээлэл таны захиалга болон мэдэгдэл хэсэгт харагдах болно.",
    orderCreationFailed: "Захиалга үүсгэхэд алдаа гарлаа.",
    contactInformation: "Холбоо барих мэдээлэл",
    overallRating: "Ерөнхий үнэлгээ",
    views: "үзэлт",
    ratingOutOf10: "{{rating}}/10",
    basedOnReviews: "({{reviewCount}} үнэлгээ)",
    noReviewsYet: "Одоогоор үнэлгээ байхгүй",
    registeredAt: "Бүртгүүлсэн огноо",
    translatorDescription: "Орчуулагчийн танилцуулга",
    notProvided: "Оруулаагүй",
    viewContactInfoButton: "Холбоо барих мэдээлэл харах",
    // Detail pages for other services
    hotelDetailTitle: "Буудлын дэлгэрэнгүй",
    wechatItemDetailTitle: "WeChat үйлчилгээний дэлгэрэнгүй",
    marketDetailTitle: "Захын дэлгэрэнгүй",
    factoryDetailTitle: "Үйлдвэрийн дэлгэрэнгүй",
    hospitalDetailTitle: "Эмнэлгийн дэлгэрэнгүй",
    embassyDetailTitle: "Элчин сайдын дэлгэрэнгүй",
    itemNotFound: "Мэдээлэл олдсонгүй.",
    locationLabel: "Байршил",
    ratingLabel: "Үнэлгээ",
    descriptionLabel: "Тайлбар",
    // Orders Page
    orderStatusPendingConfirmation: "Баталгаажуулалт хүлээгдэж байна",
    orderStatusConfirmed: "Баталгаажсан",
    orderStatusContactRevealed: "Холбоо барих мэдээлэл нээгдсэн",
    orderStatusPendingPayment: "Төлбөр хүлээгдэж байна",
    orderStatusCancelled: "Цуцлагдсан",
    orderStatusCompleted: "Дууссан",
    orderDate: "Захиалсан огноо",
    orderServiceName: "Үйлчилгээний нэр",
    orderAmount: "Дүн",
    day: "өдөр",
    loadingOrders: "Захиалга уншиж байна...",
    status: "Төлөв",
    mongolianPhoneNumberLabel: "Монгол утас",
    translatorContactPhoneLabel: "Хятад утас", // Was "Утас"
    translatorContactWeChatLabel: "WeChat ID",
    translatorContactWeChatQrLabel: "WeChat QR",
    deleteOrderTitle: "Захиалга устгах",
    deleteOrderConfirmation: "Та энэ захиалгыг устгахдаа итгэлтэй байна уу? Энэ үйлдлийг буцаах боломжгүй.",
    deleteButtonLabel: "Устгах",
    orderDeletedSuccessTitle: "Амжилттай",
    orderDeletedSuccessDesc: "Захиалга устгагдлаа.",
    orderDeletionErrorGeneric: "Захиалга устгахад алдаа гарлаа.",
    orderDeletionErrorFirebase: "Firestore-оос захиалга устгахад алдаа гарлаа.",
    // Notification Deletion
    deleteNotification: "Мэдэгдэл устгах",
    confirmDeletionTitle: "Устгахдаа итгэлтэй байна уу?",
    confirmDeletionNotificationDesc: "Энэ мэдэгдлийг устгах уу? Энэ үйлдлийг буцаах боломжгүй.",
    deleteButtonConfirm: "Устгах",
    notificationDeletedSuccessTitle: "Амжилттай",
    notificationDeletedSuccessDesc: "Мэдэгдэл устгагдлаа.",
    notificationDeletionErrorGeneric: "Мэдэгдэл устгахад алдаа гарлаа.",
    notificationDeletionErrorFirebase: "Firestore-оос мэдэгдэл устгахад алдаа гарлаа.",
    // Hotel Detail Page specific
    roomsTitle: "Өрөөнүүд",
    roomImageAlt: "Өрөөний зураг",
    noRoomDescription: "Өрөөний тайлбар байхгүй.",
    hotelInquiryPaymentModalTitle: "Лавлагааны төлбөр",
    hotelInquiryPaymentModalDescription: "{{serviceName}} буудлын талаар лавлагаа хийхэд {{amount}} юанийн үйлчилгээний хураамжтай.",
    hotelInquirySubmittedTitle: "Лавлагаа амжилттай",
    hotelInquirySubmittedDesc: "{{serviceName}} буудлын талаарх таны лавлагааг хүлээн авлаа. Дэлгэрэнгүй мэдээллийг захиалга хэсгээс харна уу.",
    // Review Form
    giveRatingTitle: "Үнэлгээ өгөх",
    ratingScaleBad: "Муу",
    ratingScaleGood: "Сайн",
    reviewCommentTitle: "Сэтгэгдэл",
    reviewCommentPlaceholder: "Сэтгэгдэл бичих...",
    submitReviewButton: "Илгээх",
    loginToReview: "Сэтгэгдэл бичихийн тулд нэвтэрнэ үү.",
    reviewSubmittedSuccess: "Таны үнэлгээ, сэтгэгдэл амжилттай хадгалагдлаа.",
    reviewSubmitError: "Үнэлгээ, сэтгэгдэл хадгалахад алдаа гарлаа.",
    selectRatingPrompt: "Үнэлгээгээ сонгоно уу (1-10).",
    reviewFormCardTitle: "Үнэлгээ болон сэтгэгдэл",
    yourRating: "Таны үнэлгээ",
    averageRatingDisplay: "{{averageRating}} ({{reviewCount}} үнэлгээ)",
    // Auth Error Messages
    authErrorTitle: "Алдаа",
    authErrorInvalidCredential: "И-мэйл эсвэл нууц үг буруу байна.",
    authErrorInvalidEmail: "И-мэйл хаягийн формат буруу байна.",
    authErrorEmailAlreadyInUse: "Энэ и-мэйл хаяг бүртгэлтэй байна.",
    authErrorWeakPassword: "Нууц үг хэт сул байна (дор хаяж 6 тэмдэгт).",
    authErrorTooManyRequests: "Хэт олон амжилтгүй оролдлого. Түр хүлээгээд дахин оролдоно уу.",
    authErrorGenericLogin: "Нэвтрэхэд алдаа гарлаа. Дахин оролдоно уу.",
    authErrorGenericRegister: "Бүртгүүлэхэд алдаа гарлаа. Дахин оролдоно уу.",
    // Subcategory filtering
    allSubcategories: "Бүх дэд ангилал",
    filterBySubcategory: "Дэд ангиллаар шүүх",
    allCategoriesFilter: "Бүгд", // For Saved page filter
    genderMale: "Эр",
    genderFemale: "Эм",
    genderOther: "Бусад",
    noSearchResultsPlaceholder: "Хайлтын үр дүн олдсонгүй.",
    // Profile Picture Update
    changeProfilePictureAria: "Профайл зураг солих",
    profilePictureUpdateSuccess: "Профайл зураг амжилттай шинэчлэгдлээ.",
    profilePictureUpdateError: "Профайл зураг шинэчлэхэд алдаа гарлаа.",
    invalidFileTypeProfile: "Зөвхөн JPG, PNG, GIF төрлийн зураг оруулна уу.",
    fileTooLargeProfile: "Зургийн хэмжээ {{maxSize}}-с ихгүй байх ёстой.",
    uploadFailedError: "Зураг байршуулахад алдаа гарлаа.",
    // City Selection Sheet
    majorCitiesTitle: "Том хотууд",
    otherCitiesTitle: "Бусад хотууд",

  },
  cn: {
    bookNowButton: "立即预订",
    orderNowButton: "立即下单",
    inquireButton: "咨询",
    orderSuccessNotificationTitle: "订单成功",
    orderSuccessNotificationDescription: "您已成功预订 {{serviceName}} 服务。",
    orderFailedNotificationTitle: "订单失败",
    orderFailedNotificationDescription: "预订 {{serviceName}} 服务时出错。",
    loginToProceed: "请登录后继续。",
    loginToBookService: "请登录以预订服务。",
    // Header & Nav
    citySelectorPlaceholder: "选择城市",
    citySelectorAriaLabel: "城市选择器",
    allCities: "全部",
    login: "登录",
    register: "注册",
    logout: "登出",
    profile: "个人资料",
    home: "首页",
    orders: "订单",
    saved: "已保存",
    notifications: "通知",
    user: "用户", // For BottomNav
    // Service Groups
    flights: "机票",
    hotels: "酒店",
    translators: "翻译",
    wechat: "微信服务",
    markets: "市场/购物",
    factories: "工厂",
    hospitals: "医院",
    embassies: "大使馆",
    // Suggested Services Titles
    recommended_translators: "推荐翻译",
    recommended_hotels: "推荐酒店",
    recommended_markets: "推荐市场",
    recommended_factories: "推荐工厂",
    recommended_hospitals: "推荐医院",
    recommended_embassies: "推荐大使馆",
    recommendedWeChatServices: "推荐微信服务",
    // General
    loading: "加载中...",
    viewAll: "查看全部",
    noRecommendations: "暂无推荐。",
    search: "搜索",
    searchPlaceholder: "搜索 (例如: 酒店, 翻译)",
    serviceTypes: "服务类型",
    viewDetails: "查看详情",
    addToFavorites: "添加到收藏",
    removeFromFavorites: "从收藏中删除",
    fetchErrorGeneric: "获取数据时出错。",
    serviceImageDefaultAlt: "服务图片",
    serviceUnnamed: "未命名服务",
    // Banners (example alt texts)
    banner_promo1_alt: "促销1",
    banner_promo2_alt: "特色服务",
    // Page specific
    myOrders: "我的订单",
    mySavedItems: "我保存的项目",
    myNotifications: "我的通知",
    noOrdersPlaceholder: "您目前没有订单。",
    ordersNoPurchasesMade: "您还没有购买任何商品",
    wechatOrdersTab: "微信服务",
    noSavedItemsPlaceholder: "您目前没有已保存的项目。",
    noNotificationsPlaceholder: "您目前没有通知。",
    email: "电子邮件",
    password: "密码",
    displayName: "昵称",
    confirmPassword: "确认密码",
    alreadyHaveAccount: "已有账户？登录",
    dontHaveAccount: "没有账户？注册",
    // Profile & Settings
    settings: "设置",
    notificationSettings: "通知设置",
    manageNotificationPreferences: "管理您的电子邮件和应用内通知。",
    emailNotifications: "电子邮件通知",
    receiveUpdatesViaEmail: "通过电子邮件接收更新。",
    pushNotifications: "推送通知",
    getRealtimeAppAlerts: "获取实时应用内提醒。",
    appearanceSettings: "外观设置",
    customizeAppLook: "自定义应用程序的外观。",
    darkMode: "深色模式",
    enableDarkTheme: "启用深色主题。",
    accountSecurity: "账户安全",
    manageSecuritySettings: "管理您的密码和其他安全设置。",
    currentPassword: "当前密码",
    newPassword: "新密码",
    updatePassword: "更新密码",
    saveAllSettings: "保存所有设置",
    saveChanges: "保存更改",
    cancel: "取消",
    edit: "编辑",
    accountSettings: "账户设置",
    userProfile: "用户资料",
    enterCredentialsLogin: "请输入您的凭据以登录。",
    createYourAccount: "创建您的 Mongol 账户。",
    // Notification specific
    notification_update_title: "系统更新",
    notification_update_desc: "应用程序已更新。查看新功能。",
    unknownNotificationTitle: "通知",
    unknownNotificationDescription: "您有一条新通知。",
    translatorContactRevealedNotificationDescription: "翻译员 {{serviceName}}: 电话: {{translatorPhoneNumber}}, 微信: {{translatorWeChatId}}.",
    // Flight Search Page
    flightsPageTitle: "航班",
    selectDepartureDate: "选择出发日期",
    selectDatePlaceholder: "选择日期",
    passengers: "乘客",
    onePassenger: "1名乘客",
    twoPassengers: "2名乘客",
    threePassengers: "3名乘客",
    fourPassengers: "4名乘客",
    searchFlights: "搜索航班",
    swapAirports: "交换方向",
    back: "返回",
    fromCity: "从 (城市)",
    toCity: "到 (城市)",
    departureCityPlaceholder: "选择出发城市",
    arrivalCityPlaceholder: "选择到达城市",
    departureCityRequired: "出发城市为必填项",
    arrivalCityRequired: "到达城市为必填项",
    selectCityDialogTitle: "选择城市",
    searchCitiesPlaceholder: "搜索城市",
    noCitiesFound: "未找到城市",
    // Hotels Page
    hotelsPageTitle: "酒店",
    allSectionTitle: "全部",
    fetchHotelsError: "获取酒店数据时出错。",
    noHotelsFound: "未找到所选城市的酒店。",
    loginToBookHotel: "请登录以预订酒店。",
    // Profile Page
    profilePageTitle: "用户中心",
    personalInfo: "个人信息",
    personalInfoProgress: "个人信息已完成 {{percent}}",
    totalPoints: "您的总积分",
    phoneNumber: "电话号码",
    changePassword: "修改密码",
    purchaseHistory: "购买历史",
    registerAsTranslator: "注册成为翻译员",
    helpSupport: "帮助与支持",
    logoutSystem: "退出系统",
    n_a: "无",
    enterPhoneNumberPlaceholder: "请输入您的电话号码",
    phoneNumberUpdateSuccess: "电话号码更新成功。",
    phoneNumberUpdateError: "更新电话号码时出错。",
    // Translators Page
    translatorsPageTitle: "翻译",
    translatorsSectionTitle: "翻译员",
    addTranslator: "添加翻译员",
    statusActive: "在线",
    монгол: "蒙古语",
    идэвхтэй: "在线",
    testLevel: "考试等级",
    speaking: "口语",
    writing: "写作",
    workedBefore: "工作经验",
    yes: "是",
    no: "否",
    fields: "领域",
    price: "价格",
    // Hospitals Page
    hospitalsPageTitle: "医院",
    allHospitalsSectionTitle: "医院列表",
    // Embassies Page
    embassiesPageTitle: "大使馆",
    embassiesListingTitle: "大使馆/领事馆列表",
    // WeChat Page
    wechatPageTitle: "实用微信服务",
    // Factories Page
    factoriesPageTitle: "工厂",
    allFactoriesSectionTitle: "所有工厂",
    productShowcaseTitle: "产品展示",
    productImageAlt: "产品图片",
    noProductDescription: "暂无产品描述。",
    // Markets Page
    marketsPageTitle: "市场/购物",
    allMarketsSectionTitle: "市场和购物中心",
    // Save/Favorite functionality
    loginToSave: "请登录以保存",
    itemSaved: "已成功保存",
    itemRemovedFromSaved: "已成功从收藏中移除",
    errorSavingItem: "保存时出错",
    errorRemovingItem: "移除时出错",
    errorCheckingSaveStatus: "检查保存状态时出错",
    registrationSuccess: "注册成功",
    welcome: "欢迎！",
    registrationFailed: "注册失败",
    registrationError: "注册时发生错误。",
    error: "错误",
    passwordsDoNotMatchError: "密码不匹配。",
    registrationSuccessVerifyEmail: "验证链接已发送至您的电子邮箱。请在登录前进行验证。",
    loginFailed: "登录失败",
    loginFailedEmailNotVerified: "您的电子邮件未经验证。请检查您的电子邮件并进行验证。",
    // Password Update specific
    changePasswordPageTitle: "修改密码",
    currentPasswordLabel: "旧密码",
    newPasswordLabel: "新密码",
    confirmNewPasswordLabel: "确认新密码",
    currentPasswordPlaceholder: "旧密码",
    newPasswordPlaceholder: "新密码",
    confirmNewPasswordPlaceholder: "确认新密码",
    passwordUpdateSuccess: "密码更新成功！",
    passwordUpdateError: "更新密码时出错。",
    reauthFailedError: "当前密码错误，请重新检查。",
    passwordTooWeakError: "密码太弱。必须至少包含6个字符。",
    passwordTooWeakErrorGeneral: "密码太弱。请选择一个更强的密码。",
    genericPasswordError: "更新密码时发生意外错误。",
    userNotLoggedInError: "用户未登录。",
    passwordRequiresRecentLogin: "此操作很敏感，需要最近的身份验证。请重新登录后再试此请求。",
    settingsSavedMsg: "设置已成功保存（密码除外）。",
    passwordReqLength_8_50: "长度为 8 - 50 个字符",
    passwordReqComplexity: "至少包含 1 个大写字母、1 个小写字母、1 个数字和 1 个特殊字符",
    passwordReqSpecialCharsDetail: "允许的特殊字符: {{chars}}",
    passwordReqUppercase: "大写字母: A-Z",
    passwordReqLowercase: "小写字母: a-z",
    passwordReqMatch: "两个新密码必须相同",
    passwordReqLengthError: "密码长度必须介于8到50个字符之间。",
    passwordReqUppercaseError: "密码必须至少包含一个大写字母 (A-Z)。",
    passwordReqLowercaseError: "密码必须至少包含一个小写字母 (a-z)。",
    passwordReqNumberError: "密码必须至少包含一个数字 (0-9)。",
    passwordReqSpecialCharError: "密码必须至少包含一个特殊字符。",
    continueButton: "继续",
    // Translator Registration
    registerAsTranslatorPageTitle: "注册成为翻译员",
    translatorRegistrationFormTitle: "翻译员信息",
    translatorRegistrationFormDescription: "请填写您的翻译员信息以完成注册。",
    submitRegistration: "提交注册",
    registrationSuccessful: "注册成功！",
    registrationFailedGeneral: "注册失败，请重试。",
    fillAllFields: "请填写所有必填字段。",
    mustBeLoggedInToRegister: "您需要登录才能注册成为翻译员。",
    translatorFormStep1: "基本信息",
    translatorFormStep2: "上传文件",
    nationalityLabel: "国籍",
    selectNationalityPlaceholder: "请选择您的国籍",
    mongolian: "蒙古",
    chinese: "中国",
    innerMongolian: "内蒙古",
    inChinaNowLabel: "您目前在中国吗？",
    yearsInChinaLabel: "您在中国居住多少年了？",
    yearsInChinaPlaceholder: "年数",
    currentCityInChinaLabel: "您目前在中国的哪个城市？",
    selectCurrentCityInChinaPlaceholder: "选择城市",
    chineseExamTakenLabel: "您是否参加过汉语水平考试？",
    chineseExamDetailsLabel: "考试名称/级别",
    speakingLevelLabel: "口语水平",
    selectSpeakingLevelPlaceholder: "选择口语水平",
    writingLevelLabel: "书写水平",
    selectWritingLevelPlaceholder: "选择书写水平",
    languageLevelGood: "良好",
    languageLevelIntermediate: "中等",
    languageLevelBasic: "基础",
    workedAsTranslatorLabel: "您以前做过翻译工作吗？",
    translationFieldsLabel: "可翻译领域",
    fieldTourism: "旅游",
    fieldMedical: "医疗",
    fieldEquipment: "设备",
    fieldExhibition: "展会",
    fieldOfficialDocuments: "公文翻译",
    fieldOfficialSpeech: "正式口译",
    fieldMachinery: "机械",
    canWorkInOtherCitiesLabel: "是否可在其他城市工作",
    dailyRateLabel: "您每日的翻译费率 (人民币)",
    selectDailyRatePlaceholder: "选择费率范围",
    rate100to200: "100-200元",
    rate200to300: "200-300元",
    rate300to400: "300-400元",
    rate400to500: "400-500元",
    rate500plus: "500元以上",
    chinaPhoneNumberLabel: "中国手机号码",
    chinaPhoneNumberPlaceholder: "手机号码",
    wechatIdLabel: "微信号",
    wechatIdPlaceholder: "微信号",
    nextStepButton: "下一步",
    previousStepButton: "上一步",
    idCardFrontImageLabel: "身份证正面照片",
    idCardBackImageLabel: "身份证反面照片",
    selfieImageLabel: "本人手持身份证照片 (自拍)",
    wechatQrImageLabel: "微信二维码照片",
    selectFileButton: "选择文件",
    fileSelected: "已选择: {{fileName}}",
    noFileSelected: "未选择文件",
    uploadImagesDescription: "请上传所需文件。",
    submitApplicationButton: "提交申请",
    applicationSubmittedSuccessTitle: "申请已成功提交！",
    applicationSubmittedSuccessDescription: "我们已收到您的信息，并将尽快与您联系。",
    backToProfileButton: "返回个人中心",
    fileSizeError: "文件 {{fileName}} 大小超出限制 (最大: 5MB)。",
    idCardFrontImageSizeError: "身份证正面照片大小超出限制 (最大: 5MB)。",
    idCardBackImageSizeError: "身份证反面照片大小超出限制 (最大: 5MB)。",
    selfieImageSizeError: "自拍照大小超出限制 (最大: 5MB)。",
    wechatQrImageSizeError: "微信二维码照片大小超出限制 (最大: 5MB)。",
    requiredError: "此字段为必填项。",
    invalidNumberError: "请输入有效的数字。",
    // Help & Support Page
    helpSupportPageTitle: "帮助与支持",
    helpSupportPageSubtitle: "如果您遇到任何问题，请联系我们或查看常见问题。",
    faqTitle: "常见问题解答",
    faqSubtitle: "许多用户感兴趣的问题和答案。",
    contactSupportTitle: "联系我们",
    contactSupportSubtitle: "我们随时准备为您提供帮助。",
    emailSupportTitle: "通过电子邮件联系",
    emailSupportDescription: "请将您的问题和建议发送给我们。",
    phoneSupportTitle: "通过电话联系",
    phoneSupportDescription: "如需紧急帮助，请致电。",
    noFaqsAvailable: "目前没有常见问题。",
    helpFaq1Question: "如何更改密码？",
    helpFaq1Answer: "进入个人资料设置，点击“更改密码”选项，然后按照说明输入您的新密码。",
    helpFaq2Question: "如何注册成为翻译员？",
    helpFaq2Answer: "进入个人资料页面的“注册成为翻译员”部分，并填写必要信息。",
    helpFaq3Question: "在哪里可以查看我保存的项目？",
    helpFaq3Answer: "点击底部导航栏中的“已保存”图标，即可查看所有已保存的服务和项目。",
    faqTopicAppUsage: "应用使用指南",
    faqTopicCheapTravel: "如何经济出行?",
    termsOfService: "服务条款",
    privacyPolicy: "隐私政策",
    otherInformationTitle: "其他信息",
    // Personal Information Form
    personalInfoFormTitle: "个人信息",
    personalInfoFormDescription: "请输入您的个人信息。",
    lastName: "姓氏",
    yourLastNamePlaceholder: "您的姓氏",
    firstName: "名字",
    yourFirstNamePlaceholder: "您的名字",
    dateOfBirth: "出生日期",
    selectDatePlaceholderShort: "选择日期",
    gender: "性别",
    selectGenderPlaceholder: "选择性别",
    male: "男性",
    female: "女性",
    other: "其他",
    homeAddress: "家庭住址",
    yourHomeAddressPlaceholder: "您的家庭住址",
    save: "保存",
    personalInfoUpdateSuccess: "个人信息更新成功。",
    personalInfoUpdateError: "更新个人信息时出错。",
    fillRequiredFields: "请输入必填项。",
    // Translator Detail Page
    translatorDetailTitle: "翻译员详情",
    translatorNotFound: "未找到翻译员。",
    getContactInfoButton: "获取联系方式",
    contactInfoPaymentPlaceholder: "支付后可查看联系方式。",
    paymentModalTitle: "支付",
    paymentModalDescription: "{{rate}} 元后即可获取翻译员联系方式。",
    paymentModalDescriptionNoRate: "获取翻译员联系方式需支付服务费。",
    payButton: "支付",
    orderCreatedSuccess: "订单创建成功！",
    contactInfoAvailableInOrders: "联系信息将在您的订单和通知中显示。",
    orderCreationFailed: "订单创建失败。",
    contactInformation: "联系信息",
    overallRating: "综合评分",
    views: "次查看",
    ratingOutOf10: "{{rating}}/10",
    basedOnReviews: "({{reviewCount}} 条评价)",
    noReviewsYet: "暂无评价",
    registeredAt: "注册日期",
    translatorDescription: "翻译员简介",
    notProvided: "未提供",
    viewContactInfoButton: "查看联系方式",
    // Detail pages for other services
    hotelDetailTitle: "酒店详情",
    wechatItemDetailTitle: "微信服务详情",
    marketDetailTitle: "市场详情",
    factoryDetailTitle: "工厂详情",
    hospitalDetailTitle: "医院详情",
    embassyDetailTitle: "大使馆详情",
    itemNotFound: "未找到项目。",
    locationLabel: "地点",
    ratingLabel: "评分",
    descriptionLabel: "描述",
    // Orders Page
    orderStatusPendingConfirmation: "等待确认",
    orderStatusConfirmed: "已确认",
    orderStatusContactRevealed: "联系方式已解锁",
    orderStatusPendingPayment: "等待付款",
    orderStatusCancelled: "已取消",
    orderStatusCompleted: "已完成",
    orderDate: "订单日期",
    orderServiceName: "服务名称",
    orderAmount: "金额",
    day: "天",
    loadingOrders: "正在加载订单...",
    status: "状态",
    mongolianPhoneNumberLabel: "蒙古电话",
    translatorContactPhoneLabel: "中国电话",
    translatorContactWeChatLabel: "微信号",
    translatorContactWeChatQrLabel: "微信二维码",
    deleteOrderTitle: "删除订单",
    deleteOrderConfirmation: "您确定要删除此订单吗？此操作无法撤销。",
    deleteButtonLabel: "删除",
    orderDeletedSuccessTitle: "成功",
    orderDeletedSuccessDesc: "订单已成功删除。",
    orderDeletionErrorGeneric: "删除订单时出错。",
    orderDeletionErrorFirebase: "从 Firestore 删除订单时出错。",
    // Notification Deletion
    deleteNotification: "删除通知",
    confirmDeletionTitle: "确认删除吗？",
    confirmDeletionNotificationDesc: "您确定要删除此通知吗？此操作无法撤销。",
    deleteButtonConfirm: "删除",
    notificationDeletedSuccessTitle: "成功",
    notificationDeletedSuccessDesc: "通知已删除。",
    notificationDeletionErrorGeneric: "删除通知时出错。",
    notificationDeletionErrorFirebase: "从 Firestore 删除通知时出错。",
    // Hotel Detail Page specific
    roomsTitle: "房间",
    roomImageAlt: "房间图片",
    noRoomDescription: "暂无房间描述。",
    hotelInquiryPaymentModalTitle: "咨询费用",
    hotelInquiryPaymentModalDescription: "咨询 {{serviceName}} 酒店需支付 {{amount}} 元服务费。",
    hotelInquirySubmittedTitle: "咨询成功",
    hotelInquirySubmittedDesc: "已收到您对 {{serviceName}} 酒店的咨询。详情请查看订单。",
    // Review Form
    giveRatingTitle: "评价",
    ratingScaleBad: "差",
    ratingScaleGood: "好",
    reviewCommentTitle: "评论",
    reviewCommentPlaceholder: "写下您的评论...",
    submitReviewButton: "提交",
    loginToReview: "请登录以发表评论。",
    reviewSubmittedSuccess: "您的评价已成功提交。",
    reviewSubmitError: "提交评价时出错。",
    selectRatingPrompt: "请选择您的评分 (1-10)。",
    reviewFormCardTitle: "评分与评论",
    yourRating: "您的评分",
    averageRatingDisplay: "{{averageRating}} ({{reviewCount}} 条评价)",
    // Auth Error Messages
    authErrorTitle: "错误",
    authErrorInvalidCredential: "电子邮件或密码错误。",
    authErrorInvalidEmail: "电子邮件格式错误。",
    authErrorEmailAlreadyInUse: "此电子邮件地址已被注册。",
    authErrorWeakPassword: "密码太弱 (至少6个字符)。",
    authErrorTooManyRequests: "尝试次数过多。请稍后再试。",
    authErrorGenericLogin: "登录时发生错误。请重试。",
    authErrorGenericRegister: "注册时发生错误。请重试。",
    // Subcategory filtering
    allSubcategories: "所有子类别",
    filterBySubcategory: "按子类别筛选",
    allCategoriesFilter: "全部",
    genderMale: "男",
    genderFemale: "女",
    genderOther: "其他",
    noSearchResultsPlaceholder: "未找到搜索结果。",
    // Profile Picture Update
    changeProfilePictureAria: "更改个人资料图片",
    profilePictureUpdateSuccess: "个人资料图片更新成功。",
    profilePictureUpdateError: "更新个人资料图片时出错。",
    invalidFileTypeProfile: "请仅上传 JPG、PNG 或 GIF 类型的图片。",
    fileTooLargeProfile: "图片大小不得超过 {{maxSize}}。",
    uploadFailedError: "图片上传失败。",
    // City Selection Sheet
    majorCitiesTitle: "主要城市",
    otherCitiesTitle: "其他城市",
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('mn');

  useEffect(() => {
    const savedLang = localStorage.getItem('appLanguage') as Language | null;
    if (savedLang && (savedLang === 'mn' || savedLang === 'cn')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = useCallback((key: string, replacements?: Record<string, string | number | null | undefined>, fallback?: string): string => {
    let translation = translations[language]?.[key] || translations['mn']?.[key] || fallback || key;
    if (replacements) {
      Object.entries(replacements).forEach(([placeholder, value]) => {
        const valueStr = (value === null || value === undefined) ? '' : (typeof value === 'number' ? value.toString() : value);
        translation = translation.replace(new RegExp(`{{${placeholder}}}`, 'g'), valueStr);
      });
    }
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

    