
import type { LucideIcon } from 'lucide-react';
import type { Timestamp } from 'firebase/firestore';

export type Language = 'mn' | 'cn';

export interface City {
  value: string;
  label: string;
  label_cn?: string;
}

export interface Airport {
  value: string; // IATA code
  label: string; // Display label, e.g., City / City_MN (IATA)
  city: string;
  iata: string;
  searchTerms: string; // Concatenated string of name, mongolian name, city, iata for searching
}


export type ServiceGroupId = 'flights' | 'hotels' | 'translators' | 'wechat' | 'markets' | 'factories' | 'hospitals' | 'embassies';

export interface ServiceGroup {
  id: ServiceGroupId;
  titleKey: string; // translation key
  icon: LucideIcon;
  href: string;
}

export interface CarouselBannerItem {
  id: string;
  imageUrl: string;
  altTextKey: string; // translation key
  dataAiHint: string;
  link?: string;
}

export type ItemType = 'service' | 'translator' | 'hotel' | 'wechat' | 'promo' | 'market' | 'factory' | 'hospital' | 'embassy';


export interface RecommendedItem {
  id: string;
  name: string;
  imageUrl?: string;
  description?: string;
  gender?: string;
  city?: string;
  testLevel?: string;
  speakingLevel?: string;
  writingLevel?: string;
  hasWorkedBefore?: boolean;
  possibleFields?: string[];
  availableCities?: string[] | string;
  price?: number | string; // Can be a string like "100-200" or a number
  rating?: number;
  location?: string;
  primaryLanguage?: string;
  availabilityStatus?: string;
  dataAiHint?: string;
  itemType: ItemType; // Made mandatory
  // Fields from Translator type that might appear in RecommendedItem if it's a translator
  nationality?: Nationality;
  inChinaNow?: boolean | null;
  yearsInChina?: number | null;
  currentCityInChina?: string | null;
  chineseExamTaken?: boolean | null;
  translationFields?: TranslationField[];
  dailyRate?: DailyRateRange;
  chinaPhoneNumber?: string | null; // Keep for type consistency, but control visibility
  wechatId?: string | null; // Keep for type consistency, but control visibility
  // For WeChat items
  wechatQrImageUrl?: string;
}

export interface UserProfile {
  uid: string;
  email?: string | null;
  displayName?: string | null;
  photoURL?: string | null;
  phoneNumber?: string | null;
  lastName?: string | null;
  firstName?: string | null;
  dateOfBirth?: string | null; // Store as ISO string (YYYY-MM-DD)
  gender?: 'male' | 'female' | 'other' | null;
  homeAddress?: string | null;
  fcmTokens?: string[];
}

export interface Order {
  id?: string; // Auto-generated by Firestore if not set before addDoc, or doc.id after addDoc
  userId: string; // User who made the order
  serviceType: ItemType | string; // Type of service
  serviceId: string; // ID of the translator, flight, etc.
  serviceName: string; // Name of the service/translator
  orderDate: Timestamp | any; // Firestore Timestamp for when the order was placed
  status: 'pending_payment' | 'confirmed' | 'cancelled' | 'completed' | 'pending_confirmation';
  amount?: number | string; // Amount paid or price range
  paymentDetails?: any; // Details about the payment
  contactInfoRevealed?: boolean; // Specifically for translator orders
}


export interface SavedDocData extends RecommendedItem {
  savedAt: Timestamp | any;
}


export interface NotificationItem {
  id: string; // Firestore document ID
  titleKey: string;
  descriptionKey: string;
  descriptionPlaceholders?: Record<string, string | number>; // For dynamic text like {{serviceName}}
  date: string | Timestamp | any; // ISO string or Firestore Timestamp
  read: boolean;
  imageUrl?: string;
  dataAiHint?: string;
  link?: string; // e.g., link to the order detail page if we had one
  itemType: ItemType; // Made mandatory
}

export interface HospitalCategory {
  id: string;
  titleKey: string;
  imageUrl?: string;
  Icon?: LucideIcon;
  dataAiHint?: string;
  href: string;
  isSpecial?: boolean;
}

export interface EmbassyCategoryItem {
  id: string;
  titleKey: string;
  imageUrl: string;
  dataAiHint: string;
  href: string;
}

export interface WeChatCategoryItem {
  id: string;
  titleKey: string;
  iconType: 'lucide' | 'image';
  iconNameOrUrl: string;
  dataAiHint?: string;
  href: string;
}

// For Translator Registration Form
export type Nationality = 'mongolian' | 'chinese' | 'inner_mongolian' | '';
export type LanguageLevel = 'good' | 'intermediate' | 'basic' | '';
export type DailyRateRange = '100-200' | '200-300' | '300-400' | '400-500' | '500+' | '';
export type TranslationField = 'tourism' | 'medical' | 'equipment' | 'exhibition' | 'official_documents' | 'official_speech' | 'machinery';


export interface Translator {
  id: string;
  uid: string;
  name: string;
  photoUrl?: string | null;

  nationality?: Nationality;
  inChinaNow?: boolean | null;
  yearsInChina?: number | null;
  currentCityInChina?: string | null;
  chineseExamTaken?: boolean | null;
  speakingLevel?: LanguageLevel;
  writingLevel?: LanguageLevel;
  workedAsTranslator?: boolean | null;
  translationFields?: TranslationField[];
  canWorkInOtherCities?: string[];
  dailyRate?: DailyRateRange;
  chinaPhoneNumber?: string | null; // Sensitive
  wechatId?: string | null; // Sensitive

  // Generic fields that might overlap with RecommendedItem, ensure consistency
  city?: string; // This is 'currentCityInChina' if in China, or primary operating city
  rating?: number;
  description?: string; // Could be a short bio
  gender?: 'male' | 'female' | 'other' | null; // From user profile eventually
  itemType: ItemType; // Added to ensure translator items always have this

  idCardFrontImageUrl?: string;
  idCardBackImageUrl?: string;
  selfieImageUrl?: string;
  wechatQrImageUrl?: string;

  registeredAt?: Timestamp | any;
  isActive?: boolean;
  isProfileComplete?: boolean;
  reviewCount?: number;
  views?: number; // For display like "10/10 (436 views)"
}


export interface SavedPageItem extends RecommendedItem {
  savedAt: Timestamp | any;
}
